# Site settings
title: Galih Yudhasena
description: Blog pribadi untuk berbagi cerita, pengalaman hidup, dan opini.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://galih2d.github.io"

# Google Analytics
google_analytics: 263006714

#Pagination
paginate: 7
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
